# .github/workflows/failing-workflow.yml
name: Guaranteed Failing Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Add execute permission for ESLint
        run: chmod +x ./node_modules/.bin/eslint

      - name: Verify ESLint installation
        run: ls -la node_modules/.bin

      # Run ESLint and capture logs
      - name: Run ESLint
        id: eslint
        run: |
          npx eslint . --max-warnings 0 > build.log 2>&1  # Fail on warnings and errors
          echo "ESLint exit code: $?"  # Output the exit code for debugging

      # Only trigger this step if ESLint failed
      - name: Query Greptile On Failure
        if: steps.eslint.outcome == 'failure'  # Check if the ESLint step failed
        run: |
          if [[ -f build.log ]]; then
            LOG_CONTENT=$(< build.log)
            curl -X POST https://your-webhook-url.com/endpoint \
              -H "Content-Type: application/json" \
              -d '{
                "log": "'"${LOG_CONTENT//\'/\'\\\'\'}"'",
                "status": "failure",
                "repo": "'"${{ github.repository }}"'",
                "greptileKey": "'"${{ secrets.GREPTILE_KEY }}"'",
                "githubToken": "'"${{ secrets.GH_TOKEN }}"'"
              }'
          else
            echo "Log file not found."
          fi
