# .github/workflows/failing-workflow.yml
name: Guaranteed Failing Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Add execute permission for ESLint
        run: chmod +x ./node_modules/.bin/eslint

      # Add this step to list installed ESLint and confirm if it exists
      - name: Verify ESLint installation
        run: ls -la node_modules/.bin

      # Run ESLint using npx
      - name: Run ESLint
        run: npx eslint .

      - name: Query Greptile On Failure 5
        if: failure()
        run: |
          curl -X POST https://chic-tranquility-production.up.railway.app/debugger \
          -H "Content-Type: application/json" \
          -d '{
            "logUrl": "'"/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"'",
            "repo": "'"${{ github.repository }}"'",
            "status": "failure",
            "greptileKey": "'"${{ secrets.GREPTILE_KEY }}"'",
            "githubToken": "'"${{ github.token }}"'"
          }'
      